### ISSUE TITLE
pip installl flywheel-sdk==16.0.5rc16 and fw-heudiconv version 0.4.0 says it is incompatible

### ISSUE THREAD

**Issue by schenkerian** [PennLINC/fw-heudiconv#96]
**Describe the issue**
Installed flywheel-sdk==16.5.0rc5 and fw-heudiconv version 0.4.0 says it is incompatible. Error is: fw-heudiconv 0.4.0 has requirement flywheel-sdk~=14.6.5, but you have flywheel-sdk 16.5.0rc5.

** Were you running `fw-heudiconv` locally or from Flywheel's GUI?**
- [ ] Locally
- [ ] GUI
- [X] PMACS LPC Linux cluster install of flywheel-sdk

 - Version 0.4.0

(flywheel) [brnelson@sciget ~]$ pip install flywheel-sdk==16.5.0rc5
Collecting flywheel-sdk==16.5.0rc5
  Downloading flywheel_sdk-16.5.0rc5-py2.py3-none-any.whl (748 kB)
     |████████████████████████████████| 748 kB 3.8 MB/s
Requirement already satisfied: requests-toolbelt in /project/ftdc_misc/software/pkg/miniconda3/envs/flywheel/lib/python3.8/site-packages (from flywheel-sdk==16.5.0rc5) (0.9.1)
Requirement already satisfied: requests>=2.18.4 in /project/ftdc_misc/software/pkg/miniconda3/envs/flywheel/lib/python3.8/site-packages (from flywheel-sdk==16.5.0rc5) (2.24.0)
Requirement already satisfied: urllib3>=1.15 in /project/ftdc_misc/software/pkg/miniconda3/envs/flywheel/lib/python3.8/site-packages (from flywheel-sdk==16.5.0rc5) (1.25.11)
Requirement already satisfied: six>=1.10 in /project/ftdc_misc/software/pkg/miniconda3/envs/flywheel/lib/python3.8/site-packages (from flywheel-sdk==16.5.0rc5) (1.15.0)
Requirement already satisfied: python-dateutil in /project/ftdc_misc/software/pkg/miniconda3/envs/flywheel/lib/python3.8/site-packages (from flywheel-sdk==16.5.0rc5) (2.8.1)
Requirement already satisfied: certifi in /project/ftdc_misc/software/pkg/miniconda3/envs/flywheel/lib/python3.8/site-packages (from flywheel-sdk==16.5.0rc5) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in /project/ftdc_misc/software/pkg/miniconda3/envs/flywheel/lib/python3.8/site-packages (from requests>=2.18.4->flywheel-sdk==16.5.0rc5) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /project/ftdc_misc/software/pkg/miniconda3/envs/flywheel/lib/python3.8/site-packages (from requests>=2.18.4->flywheel-sdk==16.5.0rc5) (3.0.4)
Installing collected packages: flywheel-sdk

fw-heudiconv 0.4.0 requires flywheel-sdk~=14.6.5, but you'll have flywheel-sdk 16.5.0rc5 which is incompatible.
Successfully installed flywheel-sdk-16.5.0rc5

**Comment by TinasheMTapera** [comment]
@schenkerian thanks for filing an issue; have you tried downgrading your flywheel-sdk version for compatibility with fw-heudiconv? You can do it in an isolated environment if preferred with conda: https://fw-heudiconv.readthedocs.io/en/latest/installation.html#install-start-up-miniconda

Then in that environment install the specific sdk version:
```
pip install 'flywheel-sdk==14.6.5' --force-reinstall
```

**Comment by TinasheMTapera** [comment]
@schenkerian just re-pinging, any updates on this issue? If not I will close it for housekeeping

**Comment by schenkerian** [comment]
Hi Tinashe,

No updates. You can close.

Thanks,
Brian

From: Tinashe Michael Tapera ***@***.***>
Sent: Monday, April 18, 2022 12:46 PM
To: PennLINC/fw-heudiconv ***@***.***>
Cc: Nelson, Brian ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [PennLINC/fw-heudiconv] pip installl flywheel-sdk==16.0.5rc16 and fw-heudiconv version 0.4.0 says it is incompatible (Issue #96)


@schenkerian<https://github.com/schenkerian> just re-pinging, any updates on this issue? If not I will close it for housekeeping
